// <auto-generated />
using System;
using CanLove_Backend.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CanLove_Backend.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CanLoveDbContext))]
    [Migration("20251214114807_AddDeletedColumnsToCases")]
    partial class AddDeletedColumnsToCases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // 此 Designer 檔案會由 EF Core 自動生成
            // 實際的模型定義在 CanLoveDbContextModelSnapshot.cs 中
            // 這裡只需要保留基本的結構即可
#pragma warning restore 612, 618
        }
    }
}
